---
title: "Solo construído no aterro encerrado da Caturrita, Santa Maria, RS"
author: "Alessandro Samuel-Rosa"
date: "28 October 2017"
# bibliography: "~/Dropbox/jabref/biblio.bib"
# csl: 
output: bookdown::html_document2
---

```{r, eval=FALSE, echo=FALSE}
# Render document
rmarkdown::render('main.Rmd', encoding = 'UTF-8', output_dir = "../docs")
```

```{r, message=FALSE, warning=FALSE}
# Load packages
library(readr)
library(magrittr)
library(dplyr)
library(sp)
library(georob)
library(latticeExtra)
```

```{r, echo=TRUE, message=FALSE, warning=FALSE}
camada <- read_csv('../data/camada.csv', locale = locale(decimal_mark = ','), na = '-', comment = 'unidade')
observacao <- read_csv('../data/observacao.csv', locale = locale(decimal_mark = ','), na = '-', comment = 'unidade')
```

```{r, echo=TRUE, message=FALSE, warning=FALSE}
camada_rep <- 
  camada %>% 
  select(-camada_numero, -camada_nome, -amostra_codigo, -profund_sup, -profund_inf) %>% 
  filter(observacao_id != 'ACC-perfil-2008')
nugget <-
  camada_rep %>% 
  group_by(observacao_id) %>% 
  summarise_each(funs(var(., na.rm = TRUE))) %>% 
  select(-observacao_id) %>% 
  summarise_each(funs(mean(., na.rm = TRUE)))
camada_uni <- 
  camada_rep %>% 
  group_by(observacao_id) %>% 
  summarise_all(funs(mean(., na.rm = TRUE)))
```

```{r}
pts_rep <- 
  observacao %>% 
  select(-coord_sistema, -coord_precisao, -coord_fonte, -pais_id, -estado_id, -municipio_id, -amostra_tipo, -amostra_quanti, 
         -amostra_area, -taxon_sibcs_2006, -profund_solum) %>% 
  merge(camada_rep, by = 'observacao_id') %>% 
  filter(observacao_id != 'ACC-perfil-2008' & observacao_data != 'xx-xx-2007') %>%
  select(-observacao_data) %>% 
  mutate(coord_x = coord_x - min(coord_x), coord_y = coord_y - min(coord_y))
coordinates(pts_rep) <- ~ coord_x + coord_y
pts_uni <- 
  observacao %>% 
  select(-coord_sistema, -coord_precisao, -coord_fonte, -pais_id, -estado_id, -municipio_id, -amostra_tipo, -amostra_quanti, 
         -amostra_area, -taxon_sibcs_2006, -profund_solum) %>%
  merge(camada_uni, by = 'observacao_id') %>% 
  filter(observacao_id != 'ACC-perfil-2008' & observacao_data != 'xx-xx-2007') %>% 
  select(-observacao_data) %>% 
  mutate(coord_x = coord_x - min(coord_x), coord_y = coord_y - min(coord_y))
coordinates(pts_uni) <- ~ coord_x + coord_y
```

```{r, fig.width=14}
pts_uni@data %>% 
  select(-observacao_id, -densidade, -areiafina_naoh_peneira) %>% 
  splom(cex = 0.5, pscales = 0, col = 'darkgray',
        varnames = c('H+Al', 'Al', 'Ca', 'Mg', 'C', 'pH', 'P', 'K', 'Na', 'Sand', 'Clay'))
```


```{r}
plot(pts_uni)
```

```{r, fig.asp=1}
# Sample variogram of the clay content
# hist(pts_rep$c_)
vario_rep <- sample.variogram(
  log(p_mehlich1_eam) ~ 1, data = pts_rep, locations = ~ coord_x + coord_y, max.lag = 130, 
  lag.dist.def = 20)
vario_uni <- sample.variogram(
  log(p_mehlich1_eam) ~ 1, data = pts_uni, locations = ~ coord_x + coord_y, max.lag = 130, 
  lag.dist.def = 20)
plot(vario, annotate.npairs = TRUE)
```

I first fit the model keeping `snugget` fixed.

```{r}
fit_classic <- georob(
  log(p_mehlich1_eam) ~ 1, pts_rep, locations = ~ coord_x + coord_y,
  param = c(nugget = 0.05, variance = 0.4, scale = 15),
  fit.param = default.fit.param(nugget = TRUE, snugget = FALSE), tuning.psi = 1000)
fit_classic
```

```{r, fig.asp=1}
plot(vario, annotate.npairs = TRUE)
lines(fit_classic)
abline(h = var(pts_uni$p_mehlich1_eam), lty = 'dashed')
```

```{r}
prof <- profilelogLik(fit_classic, data.frame(scale = seq(10, 25, length.out = 100)))
plot(loglik ~ scale, prof, type = 'l')
abline(v = fit_classic$variogram.object[[1]]$param['scale'])
```

Next I fit a model taking `snugget` into account.

```{r}
snugget <- 0.01
fit_snugget <- georob(
  log(p_mehlich1_eam) ~ 1, pts_rep, locations = ~ coord_x + coord_y,
  param = c(nugget = fit_classic$variogram.object[[1]]$param[['nugget']], 
            snugget = snugget, 
            variance = fit_classic$variogram.object[[1]]$param[['variance']] - snugget, 
            scale = fit_classic$variogram.object[[1]]$param[['scale']]),
  fit.param = default.fit.param(nugget = FALSE, snugget = TRUE, scale = TRUE), 
  tuning.psi = 1000)
fit_snugget
```

```{r, fig.asp=1}
plot(vario_rep, annotate.npairs = TRUE)
lines(fit_classic, col = 'blue')
lines(fit_snugget, col = 'red')
abline(h = var(log(pts_uni$p_mehlich1_eam), na.rm = TRUE), lty = 'dashed')
```

```{r}
prof <- profilelogLik(fit_snugget, data.frame(scale = seq(10, 30, length.out = 100)))
plot(loglik ~ scale, prof, type = 'l')
abline(v = fit_snugget$variogram.object[[1]]$param['scale'])
```


